#!/usr/bin/env bash
# This script groups visitors by IP and HTTP code and displays the number of occurrences
awk '{count[$1, $9]++} END {for (key in count) {split(key, arr, SUBSEP); printf "%5d %s %s\n", count[key], arr[1], arr[2]}}' apache-access.log | sort -nr
