#!/usr/bin/env bash
# Script to count occurrences of IP and HTTP code in Apache logs
LOG_FILE="apache-access.log"
[ ! -f "$LOG_FILE" ] && exit 1
awk 'NF >= 9 {count[$1, $9]++}
     END {
         PROCINFO["sorted_in"] = "@val_num_desc"
         for (key in count) {
             split(key, arr, SUBSEP)
             printf "%5d %s %s\n", count[key], arr[1], arr[2]
         }
     }' "$LOG_FILE"
