#!/usr/bin/env bash
# This script displays "Best School" 10 times, but on the 9th iteration also displays "Hi" after "Best School"
count=1
while [ $count -le 10 ]
do
    echo "Best School"
    if [ $count -eq 9 ]; then
        echo "Hi"
    fi
    count=$((count + 1))
done
